### ISSUE TITLE
Bot immediately crashes on start

### ISSUE THREAD

**Issue by eliwilliams** [AltusConsulting/Spark-Broadcast-Bot#2]
Hi, is this code still supported? I am unable to deploy a bot in Heroku. As soon as the bot builds, it crashes. I cannot find the logs at /app/.npm/_logs as there is no .npm folder within /app.

Any help is greatly appreciated. Thanks!

**Comment by jbogarin** [comment]
Eli,

It is. Let me check it and I'll let you know what's happening. Sorry for the trouble.

**Comment by eliwilliams** [comment]
Hi @jbogarin, sorry I didn't ask this before, but is there any other info I can provide to help the team out?

**Comment by jbogarin** [comment]
Eli,

No, already identified the issue and we are working on how to fix it. It has to do with an upstream library.

I think it should be fixed tomorrow.

**Comment by eliwilliams** [comment]
Thank you @jbogarin, I really appreciate your help with this.

I assume things are still being worked on as I can now log in to the app with Spark, but once that happens, I am faced with a "No such app" page on Heroku. It is likely that I am not setting my config vars correctly. For example, in my OAuth URL, should I leave the "&state=set_state_here" bit on the end of the URL?

Edit: per @eegnom1807's instructions, I left that param in the URL. I can talk to the bot via Spark and get responses back; I just can't manage it from the web console.

**Comment by eegnom1807** [comment]
Hi Eli Williams, yes you need to leave the "state" param in the url.
