### ISSUE TITLE
Unable to open the app

### ISSUE THREAD

**Issue by DebbieChittick** [AltusConsulting/Spark-Broadcast-Bot#3]
I've followed the instructions (nicely written).  And my bot does respond.  However, I cannot post anything or create topics, because I cannot open the application.  I receive the following error: 
![image](https://user-images.githubusercontent.com/40064828/41173579-7a3b942c-6b25-11e8-9ff0-1754ef0a2e57.png)

What am I missing?

**Comment by DebbieChittick** [comment]
Maybe it has something to do with SSO....  I'll reach out to our admin.

**Comment by eegnom1807** [comment]
Let me check it!

**Comment by eegnom1807** [comment]
Did you put the variable ALLOWED ADMIN with your account in webex team? 
Is the way to be an admin user and check the functionality, both at the same time.
For check a few minutes ago made  the deploy and works correctly.

**Comment by DebbieChittick** [comment]
I have myself as the admin and the correct domain. 
![image](https://user-images.githubusercontent.com/40064828/41230764-0262d47a-6d4f-11e8-8e73-a98185624972.png)

**Comment by DebbieChittick** [comment]
@eegnom1807 I asked my SSO Admin to check to see if he sees any errors on my login attempts and he said:  The error looks like you need to be given access by the team who wrote that app
You are logging in just fine with SSO , but the app is complaining that you do not have privileges after you log in.   

Is there something else missing?

**Comment by DebbieChittick** [comment]
I do see that I have no "Authorized Applications" under my account settings: 
![image](https://user-images.githubusercontent.com/40064828/41236080-319de144-6d5e-11e8-9015-c91a4b8d3b47.png)

**Comment by DebbieChittick** [comment]
Is there any way to troubleshoot this and determine why the application is declining my login?

**Comment by eegnom1807** [comment]
I have no "Authorized Applications" and the deploy works correctly, i saw the logs in the recently deploy and i don't see errors.


That strange, every fresh deploy work fine,  how about this:
Put the params like in the picture:

ALLOWED_DOMAINS: "@domain.com" with "@"
ALLOWED_ADMIN: "user@domain.com"
REDIRECT_URI: is the same information as PUBLIC_URL
OAUTH_URL: just copy and paste, don't edit anything in the url

In the integration scope check only: "spark:people_readRead your users’ company directory"

After that i can login in the app without any problem.

Try this changes and let me know if works.

**Comment by DebbieChittick** [comment]
I've made the changes you suggested.  the Redirect and Public_URLs were the same.  I re-copied the OAuth_URL.  And I'm sorry, it's still not working.  I know one of my consulting friends has been able to get this working.  I just don't know what the issue might be.

**Comment by eegnom1807** [comment]
Maybe if you have time i can help you in webex, send me your mail address and i send you the link.

**Comment by DebbieChittick** [comment]
Thank you, 

my email address is chittickd@ae.com and I'm EST time zone.
